
export class GestionCatastro_old{
	 flagActualizado!:number
	 flagClandestino!:number
	 //nrosuministro!:number
	 idCalle!:number
	 idEmpresa!:string
	 idSector!:number
	 sector!:string
	 idSucursal!:number
	 direccion!:string
	 ejecutado!:string
	 flagpresupuesto!:number
	 flagTransferido!:number
	 nrocalle!:string 
	 nrocatastro!:number
	 nrosolicitud!:number
	 nuevo!:number
	 //propietario!:string 
	 //PARA EL FORMULARIO
	 idDepartamento!:number
	 idProvincia!:string
	 idDistrito!:number
	 idCiclo!:number
	 idTipoFicha!:number
	 idTipoPredio!:number
	 idTipoConstruccion!:number
	 idTipoAlmacenaje!:number
	 idTipoAbastecimiento!:number
	 idRutaLectura!:number
	 idRutaDistribucion!:number
	 idTipoCorrespondencia!:number
	 idCentroPoblado!:number
	 idUrbanizacion!:number
	 idTipoDocIdentidad!:number
	 idTipoServicio!:number
	 idTipoUsuario!:number
	 idTipoActividad!:number
	 idTarifa!:number
	 idTipoResponsable!:number
	 idTipoMaterial!:number
	 idTipoAccesorioConex!:number
	 idDiametroTuboAgua!:number
	 idTipoEstConexion!:number
	 idTipoAccesorioNoReglamentado!:number
	 idTipoCorteServicio!:number
	 idTipoPavimento!:number
	 idTipoVereda!:number
	 idTipoFuga!:number
	 idTipoModeloCajaConex!:number
	 idTipollaveMedidor!:number
	 idTipoMaterialCaja!:number
	 idTipoLocalizaCaja!:number
	 idTipoEstCaja!:number
	 idTipoTapa!:number
	 idTipoEstTapa!:number
	 conCajaAgua!:number
	 conTapaAgua!:number
	 idTipoFacturacionAgua!:number
	 idTipoFacturacionMedidor!:number
	 idTipoEstMedidor!:number
	 idTipoEstLectura!:number
	 idTipoMarcaMedidor!:number
	 idTipoModelMedidor!:number
	 idTipoModelCertHomologa!:number
	 idDiametroMedidor!:number
	 idTipoCapMedidor!:number
	 idTipoPosMedidor!:number
	 idTipoMedidor!:number
	 idTipoLectura!:number
	 idTipoVerificacionMedidor!:number
	 idTipoClaseMetrologica!:number
	 idTipoResultadoVerificacionMedidor!:number
	 idTipoSituacionMedidor!:number
	 idTipoFugaAlcan!:number
	 idTipoMaterialAlcan!:number
	 idDiametroTuboAlcan!:number
	 idTipoEstConexionAlcan!:number
	 idTipoCorteServicioAlcan!:number
	 idTipoPavimentoAlcan!:number
	 idTipoVeredaAlcan!:number
	 idTipoModeloCajaAlcan!:number
	 idTipoEstCajaAlcan!:number
	 idTipoCajaAlcan!:number
	 idTipoLocalizaCajaAlcan!:number
	 idTipoTapaAlcan!:number
	 idTipoEstTapaAlcan!:number
	 conCajaAlcan!:number
	 conTapaAlcan!:number
	 sospechosoVma!:number
	 
	 //faltantes
	 nrosuministro!:number
	 codigo_antiguo!:number
	 lote!:number
	 sublote!:number
	 nropisos!:number
	 piscina!:number
	 partida_registral!:string
	 conexion_intrado!:number
	 latitud!:string
	 longitud!:string
	 medidas_lote!:string
	 medidas_laterales!:string
	 nro_direccion!:number
	 referencia!:string
	 codcliente_correspondencia!:number
	 sucursal_correspondencia!:number
	 direccion_correspondencia!:number
	 nro_correspondencia!:number
	 conexion_ejecutada!:number
	 fecha_inspeccion!:string
	 fecha_actualizacion_catas!:string
	 infocorp!:number
	 alto_consumidor!:number
	 judializado!:number
	 predio_litigio!:number
	 expediente_litigio!:string
	 propietario!:string
	 nrodocumento!:number
	 telefono!:string
	 email!:string
	 ciuu!:string
	 fecha_inicio_actividad!:string
	 varias_unidades!:number
	 domestico!:number
	 comercial!:number
	 industrial!:number
	 social!:number
	 estatal!:number
	 nro_contrato!:number
	 fecha_contrato!:string
	 nro_presupuesto!:number
	 renovacion_contrato!:number
	 firmado!:number
	 conexion_temporal!:number
	 fecha_limite_conex!:string
	 grupo_entidad!:string
	 nombre_inquilino!:string
	 nro_solicitud!:number
	 fecha_solicitud!:string
	 fecha_contrato_agua!:string
	 fecha_factibilidad!:string
	 fecha_instalacion!:string
	 codigo_proyecto!:number
	 servicio_inactivo!:number
	 fecha_limite_corte_solicitud!:string
	 impedimento_corte_servicio!:number
	 conexion_hasta_caja_vereda!:number
	 fuente_propia!:number
	 descarga_fuente_propia!:number
	 promedio_fuente_propia!:number
	 distancia_limite_derecho!:string
	 distancia_limite_izquierdo!:string
	 nro_medidor!:number
	 fecha_instalacion_medidor!:string
	 marca!:string
	 anio_fabricacion!:string //se cambio
	 relacion_q3!:number
	 fecha_verificacion!:string
	 lectura_anterior!:number
	 lectura_ultima!:number
	 consumo!:number
	 lectura_promedio!:number
	 fecha_lectura_anterior!:string
	 fecha_lectura_ultima!:string
	 observacion_lectura!:string
	 fecha_mantenimiento!:string
	 fecha_afericion_inicial!:string
	 fecha_retiro!:string
	 fecha_reinstalacion!:string
	 fecha_constratacion_laboratorio!:string
	 fecha_contrastacion_campo!:string
	 nro_medidor_anterior!:string
	 lugar_alejado!:number
	 medidor_selectivo!:number
	 medidor_propiedad_empresa!:number
	 nro_solicitud_alcan!:number
	 fecha_solicitud_alcan!:string
	 fecha_contrato_alcan!:string
	 fecha_factibilidad_alcan!:string
	 sospechoso_vma!:number
	 fecha_instalacion_adicional!:string
	 codigo_proyecto_adicional!:number
	 aguas_publiales!:number
	 emisor_desague!:number
	 distancia_limite_derecho_alca!:string
	 distancia_limite_izquierdo_alca!:string
	 servicio_inactivo_alca!:number
	 fuente_propia_alca!:number
	 desague_derivacion!:number
	 descarga_fuente_propia_alc!:number
	 zona_abastecimiento!:number
	 sector_abastecimiento!:number
	 subsector_abastecimiento!:number
	 horario_abastecimiento!:string
	 horario_inspeccion_reclamo!:string
	 dias_abastecimiento!:string
	 horas_abastecimiento!:string
	 nro_lavatorios!:number
	 nro_lavaropas!:number
	 nro_water!:number
	 nro_duchas!:number
	 nro_urinarios!:number
	 nro_grifos!:number
	 nro_habitantes!:number
	 observacion_calidad!:string
	 reservorio_conectado!:number
	 sector_operacional_calidad!:number
	 presion_agua!:number
	 frecuencia_servicio!:number
	 continuidad_servicio!:number
//se agrego parte 3
	 descarga_fuente_propia_alca!:number
	 fecha_contrastacion_laboratorio!:string

}
